# Generated by Django 6.0.3 on 2026-04-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_salon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='salon',
            name='area',
            field=models.CharField(blank=True, help_text='Neighborhood/Area', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='logo',
            field=models.ImageField(blank=True, help_text='Small logo/avatar', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='salon',
            name='price_range',
            field=models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$')], default=2),
        ),
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(help_text='Background image', upload_to='salons/'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='location',
            field=models.CharField(default='صنعاء', max_length=255),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.salon')),
            ],
        ),
        migrations.AddField(
            model_name='salon',
            name='services',
            field=models.ManyToManyField(related_name='salons', to='accounts.service'),
        ),
    ]
