# Generated by Django 6.0.3 on 2026-04-01 15:06

import salons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=9, validators=[salons.models.validate_yemen_phone])),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('shop_image', models.ImageField(upload_to='salon_requests/')),
                ('logo', models.ImageField(upload_to='salon_logos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
