# Generated by Django 6.0.3 on 2026-04-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_salonrequest_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonrequest',
            name='commercial_registration',
            field=models.ImageField(default='default.png', upload_to='salon_requests/'),
            preserve_default=False,
        ),
    ]
