# Generated by Django 6.0.3 on 2026-04-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_salonrequest_commercial_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonrequest',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
