# Generated by Django 6.0.3 on 2026-04-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_salonrequest_is_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonrequest',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salonrequest',
            name='blacklisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
